[package]
name = "querier"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true }
arrow-flight = { workspace = true }
async-trait = "0.1.68"
backoff = { path = "../backoff" }
bytes = "1.4"
cache_system = { path = "../cache_system" }
client_util = { path = "../client_util" }
data_types = { path = "../data_types" }
datafusion = { workspace = true }
datafusion_util = { path = "../datafusion_util" }
futures = "0.3"
generated_types = { path = "../generated_types" }
influxdb_iox_client = { path = "../influxdb_iox_client" }
iox_catalog = { path = "../iox_catalog" }
iox_query = { path = "../iox_query" }
iox_time = { path = "../iox_time" }
metric = { path = "../metric" }
object_store = "0.5.6"
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
parquet_file = { path = "../parquet_file" }
pin-project = "1.0"
predicate = { path = "../predicate" }
prost = { version = "0.11" }
rand = "0.8.3"
service_common = { path = "../service_common" }
service_grpc_catalog = { path = "../service_grpc_catalog"}
service_grpc_schema = { path = "../service_grpc_schema" }
service_grpc_object_store = { path = "../service_grpc_object_store" }
schema = { path = "../schema" }
sharder = { path = "../sharder" }
snafu = "0.7"
thiserror = "1.0"
tokio = { version = "1.27", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7.7" }
tonic = { version = "0.9.1" }
trace = { path = "../trace" }
trace_exporters = { path = "../trace_exporters" }
trace_http = { path = "../trace_http" }
tracker = { path = "../tracker" }
uuid = { version = "1", features = ["v4"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
assert_matches = "1.5"
insta = { version = "1.29.0", features = ["yaml"] }
iox_tests = { path = "../iox_tests" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
object_store_metrics = { path = "../object_store_metrics" }
test_helpers = { path = "../test_helpers" }
