[workspace]
# In alphabetical order
members = [
    "arrow_util",
    "backoff",
    "cache_system",
    "clap_blocks",
    "client_util",
    "compactor",
    "compactor2",
    "data_types",
    "datafusion_util",
    "dml",
    "executor",
    "generated_types",
    "grpc-binary-logger-proto",
    "grpc-binary-logger-test-proto",
    "grpc-binary-logger",
    "import",
    "influxdb_influxql_parser",
    "influxdb_iox",
    "influxdb_iox_client",
    "influxdb_line_protocol",
    "influxdb_storage_client",
    "influxdb_tsm",
    "influxdb2_client",
    "influxrpc_parser",
    "ingester",
    "ingester2",
    "iox_arrow_flight",
    "iox_catalog",
    "iox_data_generator",
    "garbage_collector",
    "iox_query",
    "iox_tests",
    "iox_time",
    "ioxd_common",
    "ioxd_compactor",
    "ioxd_ingester",
    "ioxd_ingester2",
    "ioxd_garbage_collector",
    "ioxd_querier",
    "ioxd_router",
    "ioxd_test",
    "logfmt",
    "metric",
    "metric_exporters",
    "mutable_batch",
    "mutable_batch_lp",
    "mutable_batch_pb",
    "mutable_batch_tests",
    "object_store_metrics",
    "observability_deps",
    "panic_logging",
    "parquet_file",
    "parquet_to_line_protocol",
    "predicate",
    "querier",
    "query_functions",
    "query_tests",
    "router",
    "schema",
    "service_common",
    "service_grpc_influxrpc",
    "service_grpc_flight",
    "service_grpc_namespace",
    "service_grpc_object_store",
    "service_grpc_catalog",
    "service_grpc_schema",
    "service_grpc_testing",
    "sharder",
    "sqlx-hotswap-pool",
    "test_helpers",
    "test_helpers_end_to_end",
    "trace",
    "trace_exporters",
    "trace_http",
    "tracker",
    "trogging",
    "wal",
    "workspace-hack",
    "write_buffer",
    "write_summary",
]
default-members = ["influxdb_iox"]

resolver = "2"

exclude = [
    "*.md",
    "*.txt",
    ".circleci/",
    ".editorconfig",
    ".git*",
    ".github/",
    ".kodiak.toml",
    "Dockerfile*",
    "LICENSE*",
    "buf.yaml",
    "docker/",
    "docs/",
    "massif.out.*",
    "perf/",
    "scripts/",
    "test_bench/",
    "test_fixtures/",
    "tools/",
]

[workspace.package]
version = "0.1.0"
authors = ["IOx Project Developers"]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
arrow = { version = "29.0.0" }
arrow-flight = { version = "29.0.0" }
datafusion = { git = "https://github.com/apache/arrow-datafusion.git", rev="07f49803a3d7a9e9b3c2c9a7714c1bb08db71385", default-features = false }
datafusion-proto = { git = "https://github.com/apache/arrow-datafusion.git", rev="07f49803a3d7a9e9b3c2c9a7714c1bb08db71385" }
hashbrown = { version = "0.13.2" }
parquet = { version = "29.0.0" }

# This profile optimizes for runtime performance and small binary size at the expense of longer
# build times. It's most suitable for final release builds.
[profile.release]
codegen-units = 16
debug = true
lto = "thin"

[profile.bench]
debug = true

# This profile optimizes for short build times at the expense of larger binary size and slower
# runtime performance. It's most suitable for development iterations.
[profile.quick-release]
inherits = "release"
codegen-units = 16
lto = false
incremental = true

# Per insta docs: https://insta.rs/docs/quickstart/#optional-faster-runs
[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[patch.crates-io]
# remove and bump object_store dep version once this revision is released.
# patch for https://github.com/influxdata/idpe/issues/16611
object_store = { git = 'https://github.com/apache/arrow-rs.git', rev = "f5c165acc0e6cc4b34e0eaea006aab7e5bd28d66", package = "object_store" }
