[package]
name = "ingester"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
arrow_util = { version = "0.1.0", path = "../arrow_util" }
arrow-flight = { workspace = true }
async-channel = "1.8.0"
async-trait = "0.1.68"
backoff = { version = "0.1.0", path = "../backoff" }
bytes = "1.4.0"
crossbeam-utils = "0.8.15"
data_types = { version = "0.1.0", path = "../data_types" }
datafusion.workspace = true
dml = { version = "0.1.0", path = "../dml" }
flatbuffers = "23.1.21"
futures = "0.3.28"
generated_types = { version = "0.1.0", path = "../generated_types" }
hashbrown.workspace = true
ingester_query_grpc = { path = "../ingester_query_grpc" }
iox_catalog = { version = "0.1.0", path = "../iox_catalog" }
iox_query = { version = "0.1.0", path = "../iox_query" }
iox_time = { path = "../iox_time" }
metric = { version = "0.1.0", path = "../metric" }
mutable_batch = { version = "0.1.0", path = "../mutable_batch" }
mutable_batch_pb = { version = "0.1.0", path = "../mutable_batch_pb" }
observability_deps = { version = "0.1.0", path = "../observability_deps" }
once_cell = "1.17"
parking_lot = "0.12.1"
parquet_file = { version = "0.1.0", path = "../parquet_file" }
pin-project = "1.1.0"
predicate = { version = "0.1.0", path = "../predicate" }
prost = { version = "0.11.9", default-features = false, features = ["std"] }
rand = "0.8.5"
schema = { version = "0.1.0", path = "../schema" }
service_grpc_catalog = { version = "0.1.0", path = "../service_grpc_catalog" }
sharder = { version = "0.1.0", path = "../sharder" }
test_helpers = { path = "../test_helpers", features = ["future_timeout"], optional = true }
thiserror = "1.0.40"
tokio = { version = "1.28", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = "0.7.8"
tonic = { workspace = true }
trace = { version = "0.1.0", path = "../trace" }
uuid = "1.3.3"
wal = { version = "0.1.0", path = "../wal" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1.5.0"
criterion = { version = "0.5", default-features = false, features = ["async_tokio"]}
datafusion_util = { path = "../datafusion_util" }
influxdb_iox_client = { path = "../influxdb_iox_client" }
ingester_test_ctx = { path = "../ingester_test_ctx" }
lazy_static = "1.4.0"
mutable_batch_lp = { path = "../mutable_batch_lp" }
object_store = "0.5.6"
paste = "1.0.12"
tempfile = "3.5.0"
test_helpers = { path = "../test_helpers", features = ["future_timeout"] }
tokio = { version = "1.28", features = ["macros", "time", "test-util"] }

[features]
# Export some internal types for benchmark purposes only.
benches = ["test_helpers"]

[lib]
bench = false

[[bench]]
name = "wal"
harness = false
 # Require some internal types be made visible for benchmark code.
required-features = ["benches"]

[[bench]]
name = "write"
harness = false
 # Require some internal types be made visible for benchmark code.
