[package]
name = "flightsql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
arrow-flight = { workspace = true, features = ["flight-sql-experimental"] }
arrow_util = { path = "../arrow_util" }
datafusion = { workspace = true }
observability_deps = { path = "../observability_deps" }
iox_query = { path = "../iox_query" }

# Crates.io dependencies, in alphabetical order
bytes = "1.4"
futures = "0.3"
snafu = "0.7"
once_cell = { version = "1", default-features = false }
prost = "0.11"
tokio = { version = "1.27", features = ["macros", "net", "parking_lot", "rt-multi-thread", "signal", "sync", "time"] }
tonic = "0.9.1"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
