[package]
name = "data_types"
description = "Shared data types"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
croaring = "0.8.1"
influxdb-line-protocol = { path = "../influxdb_line_protocol" }
iox_time = { path = "../iox_time" }
observability_deps = { path = "../observability_deps" }
once_cell = "1"
ordered-float = "3"
percent-encoding = "2.2.0"
schema = { path = "../schema" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "json"] }
thiserror = "1.0.40"
uuid = { version = "1", features = ["v4"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies] # In alphabetical order
proptest = "1.1.0"
test_helpers = { path = "../test_helpers" }
serde_json = "1.0.96"
